[package]
name = "concurrency_parallelism_examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "concurrent"
path = "concurrent.rs"

[[bin]]
name = "parallel"
path = "parallel.rs"

[dependencies]